tasks:
- init: >-
    git clone https://git.zabbix.com/scm/zbx/zabbix.git --depth 1 "$ZABBIX_SOURCE" &&
    cd "$ZABBIX_SOURCE" &&
    ./bootstrap.sh &&
    ./configure &&
    cd - &&
    bear make
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
  - llvm-vs-code-extensions.vscode-clangd
