language: go
compiler:
- clang
- gcc
go:
- "1.16"
dist: focal
env:
- BRANCH=master
- BRANCH=release/6.0
- BRANCH=release/5.0
services:
- docker
before_install:
- pip install pytest
before_script:
- git clone https://git.zabbix.com/scm/zbx/zabbix.git --depth 1 --single-branch --branch $BRANCH
- cd zabbix
- ./bootstrap.sh
- ./configure
- cd -
script:
- ZABBIX_SOURCE=$PWD/zabbix CFLAGS='-Wall -Wextra -Wpedantic -g -O2' make
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker-compose --file tests/docker-compose.yml up --detach
- pytest
after_failure:
- docker-compose --file tests/docker-compose.yml logs agent
