language: c
compiler:
- clang
- gcc
dist: xenial
env:
- BRANCH=master
- BRANCH=release/5.4
- BRANCH=release/5.0
- BRANCH=release/4.0
services:
- docker
sudo: true
before_install:
- sudo apt install python3-pytest
before_script:
- git clone https://git.zabbix.com/scm/zbx/zabbix.git --depth 1 --single-branch --branch $BRANCH
- cd zabbix
- ./bootstrap.sh
- ./configure
- cd -
script:
- ZABBIX_SOURCE=zabbix CFLAGS='-Wall -Wextra -Wpedantic -g -O2' make
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
- docker-compose --file tests/docker-compose.yml up --detach
- pytest-3
after_failure:
- docker-compose --file tests/docker-compose.yml logs agent
